import type { clusterMessagesEn } from "./cluster.en";

const settingLabels = { clusterNodes: "Instancje", clusterSettingPort: "Port", clusterSettingEvents: "Zdarzenia na żywo", clusterSettingFeed: "Odświeżanie feedu", clusterSettingChannels: "Synchronizacja kanałów", clusterSettingPlaylists: "Synchronizacja playlist", clusterSettingPosts: "Posty społeczności", clusterSettingLive: "Sprawdzanie live", clusterSettingAvatars: "Awatary", clusterSettingMetadata: "Metadane filmów", clusterSettingImports: "Uzupełnianie importu" };
const compactLabels: Record<string, string> = { clusterHttpRole: "HTTP" };

export const clusterMessagesPl = {
  ...settingLabels,
    clusterTab: "Klaster", clusterTitle: "Stan klastra", clusterDescription: "Bieżące heartbeat'y PostgreSQL, role węzłów, wersje i ustawienia uruchomieniowe bez sekretów.", clusterLoading: "Wczytywanie stanu klastra…", clusterHealthy: "Działa prawidłowo", clusterNeedsAttention: "Wymaga uwagi", clusterRefresh: "Odśwież", clusterRefreshFailed: "Automatyczne odświeżanie nie powiodło się", clusterLoadError: "Nie udało się wczytać stanu klastra", clusterWarningNoWorker: "Żaden węzeł online nie wykonuje zadań w tle. Pobieranie i zadania cykliczne nie będą przetwarzane.", clusterWarningMultipleWorkers: "Więcej niż jeden węzeł online wykonuje zadania w tle. Pozostaw dokładnie jeden worker, aby uniknąć powielania zadań.", clusterWarningMixedVersions: "Węzły online używają różnych wersji aplikacji. Dokończ rollout albo sprawdź wdrożenie.", clusterOnlineNodes: "Online", clusterWorkerNodes: "Workery", clusterWorkerNodesHint: "Dokładnie jeden węzeł powinien mieć YTZERO_BACKGROUND_TASKS=1.", clusterHttpNodes: "HTTP", clusterAutoRefresh: "Odświeżanie co 5 sekund. Ostatnio odłączone węzły pozostają widoczne do godziny.", clusterNoInstances: "Nie znaleziono instancji klastra", clusterNoInstancesHint: "Poczekaj na kolejny heartbeat albo sprawdź połączenie z PostgreSQL.", clusterCurrentNode: "Ten węzeł", clusterOnline: "Online", clusterOffline: "Offline", clusterWorkerRole: "Worker + HTTP", clusterHttpRole: "Tylko HTTP", clusterVersion: "Wersja", clusterStarted: "Działa", clusterLastSeen: "Kontakt", clusterRuntimeSettings: "Ustawienia uruchomieniowe", clusterDemoTitle: "Symulowany klaster", clusterDemoHint: "Te pięć węzłów to dane testowe. Panel nie pokazuje stanu prawdziwego klastra.",
  ...compactLabels,
} satisfies Record<keyof typeof clusterMessagesEn, string>;
