import type { clusterMessagesEn } from "./cluster.en";

const settingLabels = { clusterNodes: "Példányok", clusterSettingPort: "Port", clusterSettingEvents: "Élő események", clusterSettingFeed: "Hírfolyam-frissítés", clusterSettingChannels: "Csatornaszinkron", clusterSettingPlaylists: "Lejátszólista-szinkron", clusterSettingPosts: "Közösségi bejegyzések", clusterSettingLive: "Élő adások ellenőrzése", clusterSettingAvatars: "Avatarok", clusterSettingMetadata: "Videómetaadatok", clusterSettingImports: "Import kiegészítése" };
const compactLabels: Record<string, string> = { clusterOnlineNodes: "Online", clusterWorkerNodes: "Workerek", clusterHttpNodes: "HTTP", clusterVersion: "Verzió", clusterStarted: "Fut", clusterLastSeen: "Kapcsolat", clusterHttpRole: "HTTP" };

export const clusterMessagesHu = {
  ...settingLabels,
    clusterTab: "Fürt", clusterTitle: "Fürt állapota", clusterDescription: "Élő PostgreSQL-életjelek, csomópontszerepek, verziók és titkokat nem tartalmazó futási beállítások.", clusterLoading: "Fürtállapot betöltése…", clusterHealthy: "Egészséges", clusterNeedsAttention: "Figyelmet igényel", clusterRefresh: "Frissítés", clusterRefreshFailed: "Az automatikus frissítés sikertelen", clusterLoadError: "A fürt állapota nem tölthető be", clusterWarningNoWorker: "Egyetlen online csomópont sem futtat háttérfeladatokat. A letöltések és az ütemezett feladatok nem lesznek feldolgozva.", clusterWarningMultipleWorkers: "Több online csomópont futtat háttérfeladatokat. A duplikált munka elkerüléséhez pontosan egy worker maradjon.", clusterWarningMixedVersions: "Az online csomópontok eltérő alkalmazásverziókat futtatnak. Fejezd be a telepítést vagy ellenőrizd a konfigurációt.", clusterOnlineNodes: "Online csomópontok", clusterWorkerNodes: "Háttér-workerek", clusterWorkerNodesHint: "Pontosan egy csomóponton legyen YTZERO_BACKGROUND_TASKS=1.", clusterHttpNodes: "Csak HTTP-replikák", clusterAutoRefresh: "5 másodpercenként frissül. A nemrég levált csomópontok legfeljebb egy óráig láthatók.", clusterNoInstances: "Nem található fürtpéldány", clusterNoInstancesHint: "Várd meg a következő életjelet, vagy ellenőrizd a PostgreSQL-kapcsolatot.", clusterCurrentNode: "Ez a csomópont", clusterOnline: "Online", clusterOffline: "Offline", clusterWorkerRole: "Worker + HTTP", clusterHttpRole: "Csak HTTP", clusterVersion: "Verzió", clusterStarted: "Elindult", clusterLastSeen: "Utolsó életjel", clusterRuntimeSettings: "Futási beállítások", clusterDemoTitle: "Szimulált fürt", clusterDemoHint: "Ez az öt csomópont tesztadat. Nem valódi fürtállapot jelenik meg.",
  ...compactLabels,
} satisfies Record<keyof typeof clusterMessagesEn, string>;
