import type { clusterMessagesEn } from "./cluster.en";

const settingLabels = { clusterNodes: "Instâncias", clusterSettingPort: "Porta", clusterSettingEvents: "Eventos ao vivo", clusterSettingFeed: "Atualização do feed", clusterSettingChannels: "Sincronização de canais", clusterSettingPlaylists: "Sincronização de playlists", clusterSettingPosts: "Posts da comunidade", clusterSettingLive: "Verificação ao vivo", clusterSettingAvatars: "Avatares", clusterSettingMetadata: "Metadados de vídeo", clusterSettingImports: "Enriquecimento da importação" };
const compactLabels: Record<string, string> = { clusterOnlineNodes: "Online", clusterWorkerNodes: "Workers", clusterHttpNodes: "HTTP", clusterVersion: "Versão", clusterStarted: "Ativo", clusterLastSeen: "Visto", clusterHttpRole: "HTTP" };

export const clusterMessagesPtBR = {
  ...settingLabels,
    clusterTab: "Cluster", clusterTitle: "Saúde do cluster", clusterDescription: "Heartbeats PostgreSQL em tempo real, funções dos nós, versões e configurações de execução sem segredos.", clusterLoading: "Carregando o estado do cluster…", clusterHealthy: "Saudável", clusterNeedsAttention: "Requer atenção", clusterRefresh: "Atualizar", clusterRefreshFailed: "Falha na atualização automática", clusterLoadError: "Não foi possível carregar o estado do cluster", clusterWarningNoWorker: "Nenhum nó online está executando tarefas em segundo plano. Downloads e tarefas agendadas não serão processados.", clusterWarningMultipleWorkers: "Mais de um nó online executa tarefas em segundo plano. Mantenha exatamente um worker para evitar trabalho duplicado.", clusterWarningMixedVersions: "Os nós online usam versões diferentes. Conclua a implantação ou verifique a configuração.", clusterOnlineNodes: "Nós online", clusterWorkerNodes: "Workers em segundo plano", clusterWorkerNodesHint: "Exatamente um nó deve usar YTZERO_BACKGROUND_TASKS=1.", clusterHttpNodes: "Réplicas somente HTTP", clusterAutoRefresh: "Atualiza a cada 5 segundos. Nós desconectados recentemente permanecem visíveis por até uma hora.", clusterNoInstances: "Nenhuma instância encontrada", clusterNoInstancesHint: "Aguarde o próximo heartbeat ou verifique a conexão PostgreSQL.", clusterCurrentNode: "Este nó", clusterOnline: "Online", clusterOffline: "Offline", clusterWorkerRole: "Worker + HTTP", clusterHttpRole: "Somente HTTP", clusterVersion: "Versão", clusterStarted: "Iniciado", clusterLastSeen: "Último heartbeat", clusterRuntimeSettings: "Configurações de execução", clusterDemoTitle: "Cluster simulado", clusterDemoHint: "Esses cinco nós são dados de teste. Nenhum estado real do cluster está sendo exibido.",
  ...compactLabels,
} satisfies Record<keyof typeof clusterMessagesEn, string>;
