import type { clusterMessagesEn } from "./cluster.en";

const settingLabels = { clusterNodes: "Instancias", clusterSettingPort: "Puerto", clusterSettingEvents: "Eventos en vivo", clusterSettingFeed: "Actualización del feed", clusterSettingChannels: "Sincronización de canales", clusterSettingPlaylists: "Sincronización de listas", clusterSettingPosts: "Publicaciones", clusterSettingLive: "Comprobación en vivo", clusterSettingAvatars: "Avatares", clusterSettingMetadata: "Metadatos de vídeo", clusterSettingImports: "Enriquecimiento de importación" };
const compactLabels: Record<string, string> = { clusterOnlineNodes: "En línea", clusterWorkerNodes: "Workers", clusterHttpNodes: "HTTP", clusterVersion: "Versión", clusterStarted: "Activo", clusterLastSeen: "Visto", clusterHttpRole: "HTTP" };

export const clusterMessagesEs = {
  ...settingLabels,
    clusterTab: "Clúster", clusterTitle: "Estado del clúster", clusterDescription: "Pulsos de PostgreSQL en vivo, roles de nodos, versiones y ajustes de ejecución sin secretos.", clusterLoading: "Cargando el estado del clúster…", clusterHealthy: "Correcto", clusterNeedsAttention: "Requiere atención", clusterRefresh: "Actualizar", clusterRefreshFailed: "Falló la actualización automática", clusterLoadError: "No se pudo cargar el estado del clúster", clusterWarningNoWorker: "Ningún nodo conectado ejecuta tareas en segundo plano. Las descargas y tareas programadas no se procesarán.", clusterWarningMultipleWorkers: "Varios nodos conectados ejecutan tareas en segundo plano. Mantén exactamente un worker para evitar trabajo duplicado.", clusterWarningMixedVersions: "Los nodos conectados usan versiones distintas. Completa el despliegue o revisa la configuración.", clusterOnlineNodes: "Nodos conectados", clusterWorkerNodes: "Workers en segundo plano", clusterWorkerNodesHint: "Exactamente un nodo debe tener YTZERO_BACKGROUND_TASKS=1.", clusterHttpNodes: "Réplicas solo HTTP", clusterAutoRefresh: "Se actualiza cada 5 segundos. Los nodos desconectados recientemente siguen visibles hasta una hora.", clusterNoInstances: "No se encontraron instancias", clusterNoInstancesHint: "Espera al próximo pulso o comprueba la conexión con PostgreSQL.", clusterCurrentNode: "Este nodo", clusterOnline: "Conectado", clusterOffline: "Desconectado", clusterWorkerRole: "Worker + HTTP", clusterHttpRole: "Solo HTTP", clusterVersion: "Versión", clusterStarted: "Iniciado", clusterLastSeen: "Último pulso", clusterRuntimeSettings: "Ajustes de ejecución", clusterDemoTitle: "Clúster simulado", clusterDemoHint: "Estos cinco nodos son datos de prueba. No se muestra el estado de un clúster real.",
  ...compactLabels,
} satisfies Record<keyof typeof clusterMessagesEn, string>;
