import type { clusterMessagesEn } from "./cluster.en";

const settingLabels = { clusterNodes: "Instanzen", clusterSettingPort: "Port", clusterSettingEvents: "Live-Ereignisse", clusterSettingFeed: "Feed-Aktualisierung", clusterSettingChannels: "Kanalsynchronisierung", clusterSettingPlaylists: "Playlist-Synchronisierung", clusterSettingPosts: "Community-Beiträge", clusterSettingLive: "Live-Prüfung", clusterSettingAvatars: "Avatare", clusterSettingMetadata: "Videometadaten", clusterSettingImports: "Import-Anreicherung" };
const compactLabels: Record<string, string> = { clusterHttpRole: "HTTP" };

export const clusterMessagesDe = {
  ...settingLabels,
    clusterTab: "Cluster", clusterTitle: "Cluster-Zustand", clusterDescription: "Aktuelle PostgreSQL-Heartbeats, Knotenrollen, Versionen und nicht geheime Laufzeiteinstellungen.", clusterLoading: "Clusterstatus wird geladen…", clusterHealthy: "Fehlerfrei", clusterNeedsAttention: "Prüfung erforderlich", clusterRefresh: "Aktualisieren", clusterRefreshFailed: "Automatische Aktualisierung fehlgeschlagen", clusterLoadError: "Clusterstatus konnte nicht geladen werden", clusterWarningNoWorker: "Kein erreichbarer Knoten führt Hintergrundaufgaben aus. Downloads und geplante Aufgaben werden nicht verarbeitet.", clusterWarningMultipleWorkers: "Mehrere erreichbare Knoten führen Hintergrundaufgaben aus. Verwende genau einen Worker, um doppelte Aufgaben zu vermeiden.", clusterWarningMixedVersions: "Erreichbare Knoten verwenden unterschiedliche App-Versionen. Schließe das Rollout ab oder prüfe die Bereitstellung.", clusterOnlineNodes: "Online", clusterWorkerNodes: "Worker", clusterWorkerNodesHint: "Genau ein Knoten sollte YTZERO_BACKGROUND_TASKS=1 verwenden.", clusterHttpNodes: "HTTP", clusterAutoRefresh: "Aktualisierung alle 5 Sekunden. Kürzlich getrennte Knoten bleiben bis zu einer Stunde sichtbar.", clusterNoInstances: "Keine Clusterinstanzen gefunden", clusterNoInstancesHint: "Warte auf den nächsten Heartbeat oder prüfe die PostgreSQL-Verbindung.", clusterCurrentNode: "Dieser Knoten", clusterOnline: "Online", clusterOffline: "Offline", clusterWorkerRole: "Worker + HTTP", clusterHttpRole: "Nur HTTP", clusterVersion: "Version", clusterStarted: "Laufzeit", clusterLastSeen: "Kontakt", clusterRuntimeSettings: "Laufzeiteinstellungen", clusterDemoTitle: "Simulierter Cluster", clusterDemoHint: "Diese fünf Knoten sind Testdaten. Es wird kein echter Clusterstatus angezeigt.",
  ...compactLabels,
} satisfies Record<keyof typeof clusterMessagesEn, string>;
