import type { clusterMessagesEn } from "./cluster.en";

const settingLabels = { clusterNodes: "Instances", clusterSettingPort: "Port", clusterSettingEvents: "Événements en direct", clusterSettingFeed: "Actualisation du flux", clusterSettingChannels: "Synchronisation des chaînes", clusterSettingPlaylists: "Synchronisation des playlists", clusterSettingPosts: "Posts Communauté", clusterSettingLive: "Vérification du direct", clusterSettingAvatars: "Avatars", clusterSettingMetadata: "Métadonnées vidéo", clusterSettingImports: "Enrichissement des imports" };
const compactLabels: Record<string, string> = { clusterOnlineNodes: "En ligne", clusterWorkerNodes: "Workers", clusterHttpNodes: "HTTP", clusterVersion: "Version", clusterStarted: "Actif", clusterLastSeen: "Vu", clusterHttpRole: "HTTP" };

export const clusterMessagesFr = {
  ...settingLabels,
    clusterTab: "Cluster", clusterTitle: "État du cluster", clusterDescription: "Heartbeats PostgreSQL en direct, rôles des nœuds, versions et paramètres d'exécution non secrets.", clusterLoading: "Chargement de l'état du cluster…", clusterHealthy: "Opérationnel", clusterNeedsAttention: "Attention requise", clusterRefresh: "Actualiser", clusterRefreshFailed: "Échec de l'actualisation automatique", clusterLoadError: "Impossible de charger l'état du cluster", clusterWarningNoWorker: "Aucun nœud en ligne n'exécute les tâches en arrière-plan. Les téléchargements et tâches planifiées ne seront pas traités.", clusterWarningMultipleWorkers: "Plusieurs nœuds en ligne exécutent les tâches en arrière-plan. Conservez exactement un worker pour éviter les doublons.", clusterWarningMixedVersions: "Les nœuds en ligne utilisent des versions différentes. Terminez le déploiement ou vérifiez sa configuration.", clusterOnlineNodes: "Nœuds en ligne", clusterWorkerNodes: "Workers en arrière-plan", clusterWorkerNodesHint: "Un seul nœud doit avoir YTZERO_BACKGROUND_TASKS=1.", clusterHttpNodes: "Réplicas HTTP uniquement", clusterAutoRefresh: "Actualisation toutes les 5 secondes. Les nœuds récemment déconnectés restent visibles pendant une heure.", clusterNoInstances: "Aucune instance de cluster", clusterNoInstancesHint: "Attendez le prochain heartbeat ou vérifiez la connexion PostgreSQL.", clusterCurrentNode: "Ce nœud", clusterOnline: "En ligne", clusterOffline: "Hors ligne", clusterWorkerRole: "Worker + HTTP", clusterHttpRole: "HTTP uniquement", clusterVersion: "Version", clusterStarted: "Démarré", clusterLastSeen: "Dernier heartbeat", clusterRuntimeSettings: "Paramètres d'exécution", clusterDemoTitle: "Cluster simulé", clusterDemoHint: "Ces cinq nœuds sont des données de test. Aucun état réel du cluster n'est affiché.",
  ...compactLabels,
} satisfies Record<keyof typeof clusterMessagesEn, string>;
