import type { clusterMessagesEn } from "./cluster.en";

const settingLabels = { clusterNodes: "Экземпляры", clusterSettingPort: "Порт", clusterSettingEvents: "События в реальном времени", clusterSettingFeed: "Обновление ленты", clusterSettingChannels: "Синхронизация каналов", clusterSettingPlaylists: "Синхронизация плейлистов", clusterSettingPosts: "Записи сообщества", clusterSettingLive: "Проверка трансляций", clusterSettingAvatars: "Аватары", clusterSettingMetadata: "Метаданные видео", clusterSettingImports: "Дополнение импорта" };
const compactLabels: Record<string, string> = { clusterOnlineNodes: "В сети", clusterWorkerNodes: "Воркеры", clusterHttpNodes: "HTTP", clusterVersion: "Версия", clusterStarted: "Работает", clusterLastSeen: "Связь", clusterHttpRole: "HTTP" };

export const clusterMessagesRu = {
  ...settingLabels,
    clusterTab: "Кластер", clusterTitle: "Состояние кластера", clusterDescription: "Актуальные сигналы PostgreSQL, роли узлов, версии и несекретные параметры запуска.", clusterLoading: "Загрузка состояния кластера…", clusterHealthy: "Исправен", clusterNeedsAttention: "Требует внимания", clusterRefresh: "Обновить", clusterRefreshFailed: "Не удалось автоматически обновить данные", clusterLoadError: "Не удалось загрузить состояние кластера", clusterWarningNoWorker: "Ни один доступный узел не выполняет фоновые задачи. Загрузки и задачи по расписанию не будут обработаны.", clusterWarningMultipleWorkers: "Фоновые задачи выполняют несколько доступных узлов. Оставьте ровно один worker, чтобы избежать повторов.", clusterWarningMixedVersions: "Доступные узлы используют разные версии приложения. Завершите развёртывание или проверьте конфигурацию.", clusterOnlineNodes: "Доступные узлы", clusterWorkerNodes: "Фоновые worker-узлы", clusterWorkerNodesHint: "Ровно один узел должен иметь YTZERO_BACKGROUND_TASKS=1.", clusterHttpNodes: "Реплики только HTTP", clusterAutoRefresh: "Обновляется каждые 5 секунд. Недавно отключённые узлы видны до одного часа.", clusterNoInstances: "Экземпляры кластера не найдены", clusterNoInstancesHint: "Дождитесь следующего сигнала или проверьте подключение PostgreSQL.", clusterCurrentNode: "Этот узел", clusterOnline: "В сети", clusterOffline: "Не в сети", clusterWorkerRole: "Worker + HTTP", clusterHttpRole: "Только HTTP", clusterVersion: "Версия", clusterStarted: "Запущен", clusterLastSeen: "Последний сигнал", clusterRuntimeSettings: "Параметры запуска", clusterDemoTitle: "Симуляция кластера", clusterDemoHint: "Эти пять узлов — тестовые данные. Состояние реального кластера не отображается.",
  ...compactLabels,
} satisfies Record<keyof typeof clusterMessagesEn, string>;
