import type { clusterMessagesEn } from "./cluster.en";

const settingLabels = { clusterNodes: "インスタンス", clusterSettingPort: "ポート", clusterSettingEvents: "ライブイベント", clusterSettingFeed: "フィード更新", clusterSettingChannels: "チャンネル同期", clusterSettingPlaylists: "再生リスト同期", clusterSettingPosts: "コミュニティ投稿", clusterSettingLive: "ライブ確認", clusterSettingAvatars: "アバター", clusterSettingMetadata: "動画メタデータ", clusterSettingImports: "インポート補完" };
const compactLabels: Record<string, string> = { clusterOnlineNodes: "オンライン", clusterWorkerNodes: "Worker", clusterHttpNodes: "HTTP", clusterVersion: "バージョン", clusterStarted: "稼働", clusterLastSeen: "通信", clusterHttpRole: "HTTP" };

export const clusterMessagesJa = {
  ...settingLabels,
    clusterTab: "クラスター", clusterTitle: "クラスターの状態", clusterDescription: "PostgreSQL のリアルタイムハートビート、ノードの役割、バージョン、機密情報を含まない実行設定です。", clusterLoading: "クラスターの状態を読み込んでいます…", clusterHealthy: "正常", clusterNeedsAttention: "確認が必要", clusterRefresh: "更新", clusterRefreshFailed: "自動更新に失敗しました", clusterLoadError: "クラスターの状態を読み込めませんでした", clusterWarningNoWorker: "バックグラウンド処理を実行するオンラインノードがありません。ダウンロードと定期処理は実行されません。", clusterWarningMultipleWorkers: "複数のオンラインノードがバックグラウンド処理を実行しています。重複を防ぐため worker は1台だけにしてください。", clusterWarningMixedVersions: "オンラインノードのアプリバージョンが異なります。ロールアウトを完了するか、デプロイを確認してください。", clusterOnlineNodes: "オンラインノード", clusterWorkerNodes: "バックグラウンド worker", clusterWorkerNodesHint: "YTZERO_BACKGROUND_TASKS=1 のノードは1台だけにしてください。", clusterHttpNodes: "HTTP 専用レプリカ", clusterAutoRefresh: "5秒ごとに更新します。最近切断されたノードは最大1時間表示されます。", clusterNoInstances: "クラスターインスタンスがありません", clusterNoInstancesHint: "次のハートビートを待つか、PostgreSQL 接続を確認してください。", clusterCurrentNode: "このノード", clusterOnline: "オンライン", clusterOffline: "オフライン", clusterWorkerRole: "Worker + HTTP", clusterHttpRole: "HTTP のみ", clusterVersion: "バージョン", clusterStarted: "開始日時", clusterLastSeen: "最終ハートビート", clusterRuntimeSettings: "実行設定", clusterDemoTitle: "模擬クラスター", clusterDemoHint: "この5台のノードはテストデータです。実際のクラスター状態ではありません。",
  ...compactLabels,
} satisfies Record<keyof typeof clusterMessagesEn, string>;
