import { feedBuilderMessagesEn } from "./feedBuilder.en";

const firstPass = { ...feedBuilderMessagesEn, feedBuilderTitle: "フィードビルダー", feedBuilderDescription: "通常の行の間にテーマ別の完全な行を挿入し、システムセクションを配置または非表示にします。", feedBuilderMode: "フィードモード", feedBuilderClassic: "クラシック", feedBuilderComposed: "構成済み", feedBuilderRows: "行", feedBuilderSequenceOrdered: "順番", feedBuilderSequenceRandom: "ランダム", feedBuilderAddRecipe: "レシピを追加", feedBuilderRecipe: "レシピ", feedBuilderRecipeName: "レシピ名", feedBuilderDeleteRecipe: "レシピを削除", feedBuilderChannels: "チャンネル", feedBuilderTags: "タグ", feedBuilderPersonalPlaylists: "個人プレイリスト", feedBuilderSearchSources: "ソースを検索…", feedBuilderNoneSelected: "未選択", feedBuilderSelectedCount: "{count}件選択", feedBuilderDays: "日", feedBuilderHiddenExclude: "除外", feedBuilderHiddenInclude: "許可", feedBuilderHiddenOnly: "非表示のみ", feedBuilderMediaInclude: "許可", feedBuilderMediaExclude: "除外", feedBuilderMediaOnly: "この種類のみ", feedBuilderRandomOrder: "ランダム", feedBuilderPreview: "利用可能数を確認", feedBuilderPreviewCount: "候補 {count}件", feedBuilderSaved: "フィードビルダーを保存しました。", feedBuilderSaveError: "フィードビルダーを保存できませんでした。" };

export const feedBuilderMessagesJa = {
  ...firstPass,
  feedBuilderPreviewError: "利用可能数を確認できませんでした。",
  feedBuilderLoadError: "フィードビルダーを読み込めませんでした。",
  feedBuilderFeedLoadError: "フィードを読み込めませんでした。",
  feedBuilderRetry: "もう一度試す",
  feedBuilderClassicHint: "現在の時系列フィードを変更せずに使用します。", feedBuilderComposedHint: "通常のフィード行の間に設定した行を挿入します。", feedBuilderInterval: "テーマ行の間隔", feedBuilderIntervalHint: "動画数ではなく、完成した通常行の数を数えます。", feedBuilderRecipeSequence: "レシピの順序", feedBuilderRecipeSequenceHint: "保存順または安定したランダム順でレシピを選びます。", feedBuilderSystemSectionHint: "指定した通常行数の後に表示します。0は先頭です。", feedBuilderSectionVisible: "セクションを表示", feedBuilderAfterRows: "通常行の後", feedBuilderRecipes: "行レシピ", feedBuilderRecipesHint: "レシピは完全な1行を提供します。不完全な行はスキップされます。", feedBuilderNoRecipes: "テーマ行が設定されていません。構成済みフィードには通常行と表示中のシステムセクションだけが含まれます。",
  feedBuilderMoveUp: "レシピを上へ", feedBuilderMoveDown: "レシピを下へ", feedBuilderRecipeEnabled: "レシピを有効化", feedBuilderSourceScope: "ソース範囲", feedBuilderAllSources: "すべてのソース", feedBuilderAllSourcesHint: "このプロフィールで利用できるすべてのソースを使います。", feedBuilderSelectedSources: "選択したソース", feedBuilderSelectedSourcesHint: "下のチャンネル、タグ、プレイリストに一致させます。", feedBuilderIncludeMatch: "含める条件", feedBuilderMatchAny: "いずれかのグループ", feedBuilderMatchAnyHint: "動画はいずれかの空でないソースグループに一致すれば対象です。", feedBuilderMatchAll: "すべてのグループ", feedBuilderMatchAllHint: "動画はすべての空でないソースグループに一致する必要があります。",
  feedBuilderInclude: "表示可能", feedBuilderExclude: "表示禁止", feedBuilderYoutubePlaylists: "フォロー中のYouTubeプレイリスト", feedBuilderMaxAge: "最大経過日数", feedBuilderMaxAgeHint: "レシピの項目は最大183日前までです。", feedBuilderHiddenTags: "フィードで非表示のタグ", feedBuilderShorts: "Shorts", feedBuilderLive: "ライブと配信予定", feedBuilderMembersOnly: "メンバー限定", feedBuilderMediaInherit: "フィード設定に従う", feedBuilderVideoOrder: "動画の順序", feedBuilderFeedOrder: "新しい順", feedBuilderRecipeNeedsSource: "ソースを1つ以上選択してください", feedBuilderRecipeNeedsSourceHint: "チャンネル、タグ、プレイリストを選ぶまで、このレシピは空のままです。", feedBuilderConflict: "別の場所でフィードビルダーが変更されました。最新の内容を読み込みました。",
} satisfies Record<keyof typeof feedBuilderMessagesEn, string>;
