import { feedBuilderMessagesEn } from "./feedBuilder.en";

const firstPass = { ...feedBuilderMessagesEn, feedBuilderTitle: "Hírfolyam-építő", feedBuilderDescription: "Teljes tematikus sorokat illeszthetsz a normál sorok közé, a rendszerszakaszokat pedig elhelyezheted vagy elrejtheted.", feedBuilderMode: "Hírfolyammód", feedBuilderClassic: "Klasszikus", feedBuilderComposed: "Összeállított", feedBuilderRows: "sor", feedBuilderSequenceOrdered: "Sorrendben", feedBuilderSequenceRandom: "Véletlen", feedBuilderAddRecipe: "Recept hozzáadása", feedBuilderRecipe: "Recept", feedBuilderRecipeName: "Recept neve", feedBuilderDeleteRecipe: "Recept törlése", feedBuilderChannels: "Csatornák", feedBuilderTags: "Címkék", feedBuilderPersonalPlaylists: "Saját lejátszási listák", feedBuilderSearchSources: "Források keresése…", feedBuilderNoneSelected: "Nincs kiválasztva", feedBuilderSelectedCount: "{count} kiválasztva", feedBuilderDays: "nap", feedBuilderHiddenExclude: "Kizárás", feedBuilderHiddenInclude: "Engedélyezés", feedBuilderHiddenOnly: "Csak rejtettek", feedBuilderMediaInclude: "Engedélyezés", feedBuilderMediaExclude: "Kizárás", feedBuilderMediaOnly: "Csak ez a típus", feedBuilderRandomOrder: "Véletlen", feedBuilderPreview: "Elérhetőség ellenőrzése", feedBuilderPreviewCount: "{count} jelölt", feedBuilderSaved: "Hírfolyam-építő mentve.", feedBuilderSaveError: "A hírfolyam-építő mentése sikertelen." };

export const feedBuilderMessagesHu = {
  ...firstPass,
  feedBuilderPreviewError: "Az elérhetőség ellenőrzése sikertelen.",
  feedBuilderLoadError: "A hírfolyam-építő betöltése sikertelen.",
  feedBuilderFeedLoadError: "A hírfolyam betöltése sikertelen.",
  feedBuilderRetry: "Próbáld újra",
  feedBuilderClassicHint: "A jelenlegi időrendi hírfolyam változatlanul marad.", feedBuilderComposedHint: "Beállított sorokat illeszt a normál hírfolyamsorok közé.", feedBuilderInterval: "Tematikus sorok időköze", feedBuilderIntervalHint: "A teljes normál sorokat számolja, nem az egyes videókat.", feedBuilderRecipeSequence: "Receptek sorrendje", feedBuilderRecipeSequenceHint: "A recepteket mentett vagy stabil véletlen sorrendben választja.", feedBuilderSystemSectionHint: "A megadott számú normál sor után jelenik meg. A 0 a tetejét jelenti.", feedBuilderSectionVisible: "Szakasz látható", feedBuilderAfterRows: "Normál sorok után", feedBuilderRecipes: "Sorrecept", feedBuilderRecipesHint: "Egy recept egy teljes sort ad. A hiányos sorok kimaradnak.", feedBuilderNoRecipes: "Nincs tematikus sor beállítva. Az összeállított hírfolyam csak normál sorokat és látható rendszerszakaszokat tartalmaz.",
  feedBuilderMoveUp: "Recept feljebb", feedBuilderMoveDown: "Recept lejjebb", feedBuilderRecipeEnabled: "Recept engedélyezve", feedBuilderSourceScope: "Források köre", feedBuilderAllSources: "Minden forrás", feedBuilderAllSourcesHint: "A profil számára elérhető összes forrás használata.", feedBuilderSelectedSources: "Kijelölt források", feedBuilderSelectedSourcesHint: "Az alábbi csatornák, címkék vagy lejátszási listák illesztése.", feedBuilderIncludeMatch: "Belefoglalások illesztése", feedBuilderMatchAny: "Bármely csoport", feedBuilderMatchAnyHint: "A videó bármely nem üres forráscsoporthoz illeszkedhet.", feedBuilderMatchAll: "Minden csoport", feedBuilderMatchAllHint: "A videónak minden nem üres forráscsoporthoz illeszkednie kell.",
  feedBuilderInclude: "Megjelenhet", feedBuilderExclude: "Nem jelenhet meg", feedBuilderYoutubePlaylists: "Követett YouTube-listák", feedBuilderMaxAge: "Legnagyobb kor", feedBuilderMaxAgeHint: "A receptek elemei legfeljebb 183 naposak lehetnek.", feedBuilderHiddenTags: "Hírfolyamból rejtett címkék", feedBuilderShorts: "Shorts", feedBuilderLive: "Élő és közelgő", feedBuilderMembersOnly: "Csak tagoknak", feedBuilderMediaInherit: "Hírfolyam-beállítás követése", feedBuilderVideoOrder: "Videók sorrendje", feedBuilderFeedOrder: "Legújabb elöl", feedBuilderRecipeNeedsSource: "Válassz legalább egy forrást", feedBuilderRecipeNeedsSourceHint: "A recept üres marad, amíg nincs kijelölve csatorna, címke vagy lejátszási lista.", feedBuilderConflict: "A hírfolyam-építő máshol megváltozott. A legújabb verzió töltődött be.",
} satisfies Record<keyof typeof feedBuilderMessagesEn, string>;
