import { feedBuilderMessagesEn } from "./feedBuilder.en";

const firstPass = { ...feedBuilderMessagesEn, feedBuilderTitle: "Конструктор ленты", feedBuilderDescription: "Добавляйте полные тематические ряды между обычными рядами и размещайте или скрывайте системные разделы.", feedBuilderMode: "Режим ленты", feedBuilderClassic: "Классический", feedBuilderComposed: "Составной", feedBuilderRows: "рядов", feedBuilderSequenceOrdered: "По порядку", feedBuilderSequenceRandom: "Случайно", feedBuilderAddRecipe: "Добавить рецепт", feedBuilderRecipe: "Рецепт", feedBuilderRecipeName: "Название рецепта", feedBuilderDeleteRecipe: "Удалить рецепт", feedBuilderChannels: "Каналы", feedBuilderTags: "Теги", feedBuilderPersonalPlaylists: "Личные плейлисты", feedBuilderSearchSources: "Поиск источников…", feedBuilderNoneSelected: "Ничего не выбрано", feedBuilderSelectedCount: "Выбрано: {count}", feedBuilderDays: "дней", feedBuilderHiddenExclude: "Исключить", feedBuilderHiddenInclude: "Разрешить", feedBuilderHiddenOnly: "Только скрытые", feedBuilderMediaInclude: "Разрешить", feedBuilderMediaExclude: "Исключить", feedBuilderMediaOnly: "Только этот тип", feedBuilderRandomOrder: "Случайно", feedBuilderPreview: "Проверить доступность", feedBuilderPreviewCount: "Кандидатов: {count}", feedBuilderSaved: "Конструктор ленты сохранён.", feedBuilderSaveError: "Не удалось сохранить конструктор ленты." };

export const feedBuilderMessagesRu = {
  ...firstPass,
  feedBuilderPreviewError: "Не удалось проверить доступность.",
  feedBuilderLoadError: "Не удалось загрузить конструктор ленты.",
  feedBuilderFeedLoadError: "Не удалось загрузить ленту.",
  feedBuilderRetry: "Повторить",
  feedBuilderClassicHint: "Оставить текущую хронологическую ленту без изменений.", feedBuilderComposedHint: "Вставлять настроенные ряды между обычными рядами.", feedBuilderInterval: "Интервал тематических рядов", feedBuilderIntervalHint: "Считаются полные обычные ряды, а не отдельные видео.", feedBuilderRecipeSequence: "Порядок рецептов", feedBuilderRecipeSequenceHint: "Выбирать рецепты в сохранённом или стабильном случайном порядке.", feedBuilderSystemSectionHint: "Показывать раздел после выбранного числа обычных рядов. 0 означает верх.", feedBuilderSectionVisible: "Раздел видим", feedBuilderAfterRows: "После обычных рядов", feedBuilderRecipes: "Рецепты рядов", feedBuilderRecipesHint: "Рецепт формирует один полный ряд. Неполные ряды пропускаются.", feedBuilderNoRecipes: "Тематические ряды не настроены. В составной ленте останутся обычные ряды и видимые системные разделы.",
  feedBuilderMoveUp: "Переместить рецепт вверх", feedBuilderMoveDown: "Переместить рецепт вниз", feedBuilderRecipeEnabled: "Рецепт включён", feedBuilderSourceScope: "Область источников", feedBuilderAllSources: "Все источники", feedBuilderAllSourcesHint: "Использовать все источники, доступные этому профилю.", feedBuilderSelectedSources: "Выбранные источники", feedBuilderSelectedSourcesHint: "Сопоставлять указанные ниже каналы, теги или плейлисты.", feedBuilderIncludeMatch: "Правило включения", feedBuilderMatchAny: "Любая группа", feedBuilderMatchAnyHint: "Видео может соответствовать любой непустой группе источников.", feedBuilderMatchAll: "Все группы", feedBuilderMatchAllHint: "Видео должно соответствовать каждой непустой группе источников.",
  feedBuilderInclude: "Может появиться", feedBuilderExclude: "Не должно появиться", feedBuilderYoutubePlaylists: "Отслеживаемые плейлисты YouTube", feedBuilderMaxAge: "Максимальный возраст", feedBuilderMaxAgeHint: "Материалы рецепта могут быть не старше 183 дней.", feedBuilderHiddenTags: "Скрытые из ленты теги", feedBuilderShorts: "Shorts", feedBuilderLive: "Трансляции и предстоящие", feedBuilderMembersOnly: "Только для участников", feedBuilderMediaInherit: "Следовать настройке ленты", feedBuilderVideoOrder: "Порядок видео", feedBuilderFeedOrder: "Сначала новые", feedBuilderRecipeNeedsSource: "Выберите хотя бы один источник", feedBuilderRecipeNeedsSourceHint: "Рецепт останется пустым, пока не будет выбран канал, тег или плейлист.", feedBuilderConflict: "Конструктор ленты был изменён в другом месте. Загружена последняя версия.",
} satisfies Record<keyof typeof feedBuilderMessagesEn, string>;
