import { feedBuilderMessagesEn } from "./feedBuilder.en";

const firstPass = { ...feedBuilderMessagesEn, feedBuilderTitle: "Construtor do feed", feedBuilderDescription: "Insira linhas temáticas completas entre as linhas normais e posicione ou oculte seções do sistema.", feedBuilderMode: "Modo do feed", feedBuilderClassic: "Clássico", feedBuilderComposed: "Composto", feedBuilderRows: "linhas", feedBuilderSequenceOrdered: "Em ordem", feedBuilderSequenceRandom: "Aleatório", feedBuilderAddRecipe: "Adicionar receita", feedBuilderRecipe: "Receita", feedBuilderRecipeName: "Nome da receita", feedBuilderDeleteRecipe: "Excluir receita", feedBuilderChannels: "Canais", feedBuilderTags: "Tags", feedBuilderPersonalPlaylists: "Playlists pessoais", feedBuilderSearchSources: "Buscar fontes…", feedBuilderNoneSelected: "Nada selecionado", feedBuilderSelectedCount: "{count} selecionados", feedBuilderDays: "dias", feedBuilderHiddenExclude: "Excluir", feedBuilderHiddenInclude: "Permitir", feedBuilderHiddenOnly: "Somente ocultos", feedBuilderMediaInclude: "Permitir", feedBuilderMediaExclude: "Excluir", feedBuilderMediaOnly: "Somente este tipo", feedBuilderRandomOrder: "Aleatório", feedBuilderPreview: "Verificar disponibilidade", feedBuilderPreviewCount: "{count} candidatos", feedBuilderSaved: "Construtor do feed salvo.", feedBuilderSaveError: "Não foi possível salvar o construtor do feed." };

export const feedBuilderMessagesPtBR = {
  ...firstPass,
  feedBuilderPreviewError: "Não foi possível verificar a disponibilidade.",
  feedBuilderLoadError: "Não foi possível carregar o construtor do feed.",
  feedBuilderFeedLoadError: "Não foi possível carregar o feed.",
  feedBuilderRetry: "Tentar novamente",
  feedBuilderClassicHint: "Mantenha o feed cronológico atual sem alterações.", feedBuilderComposedHint: "Insira linhas configuradas entre as linhas normais.",
  feedBuilderInterval: "Intervalo das linhas temáticas", feedBuilderIntervalHint: "São contadas linhas normais completas, não vídeos individuais.", feedBuilderRecipeSequence: "Sequência de receitas", feedBuilderRecipeSequenceHint: "Escolha receitas na ordem salva ou em uma ordem aleatória estável.",
  feedBuilderSystemSectionHint: "Mostre esta seção após o número escolhido de linhas normais. Use 0 para o topo.", feedBuilderSectionVisible: "Seção visível", feedBuilderAfterRows: "Após linhas normais", feedBuilderRecipes: "Receitas de linha", feedBuilderRecipesHint: "Uma receita fornece uma linha completa. Linhas incompletas são ignoradas.", feedBuilderNoRecipes: "Nenhuma linha temática está configurada. O feed composto terá apenas linhas normais e seções do sistema visíveis.",
  feedBuilderMoveUp: "Mover receita para cima", feedBuilderMoveDown: "Mover receita para baixo", feedBuilderRecipeEnabled: "Receita ativada", feedBuilderSourceScope: "Escopo das fontes", feedBuilderAllSources: "Todas as fontes", feedBuilderAllSourcesHint: "Use todas as fontes disponíveis para este perfil.", feedBuilderSelectedSources: "Fontes selecionadas", feedBuilderSelectedSourcesHint: "Combine os canais, tags ou playlists abaixo.",
  feedBuilderIncludeMatch: "Como as inclusões combinam", feedBuilderMatchAny: "Qualquer grupo", feedBuilderMatchAnyHint: "Um vídeo pode corresponder a qualquer grupo de fontes não vazio.", feedBuilderMatchAll: "Todos os grupos", feedBuilderMatchAllHint: "Um vídeo deve corresponder a cada grupo de fontes não vazio.", feedBuilderInclude: "Pode aparecer", feedBuilderExclude: "Não pode aparecer", feedBuilderTags: "Tags", feedBuilderYoutubePlaylists: "Playlists do YouTube seguidas", feedBuilderMaxAge: "Idade máxima", feedBuilderMaxAgeHint: "Os itens de uma receita podem ter no máximo 183 dias.",
  feedBuilderHiddenTags: "Tags ocultas do feed", feedBuilderShorts: "Shorts", feedBuilderLive: "Ao vivo e próximos", feedBuilderMembersOnly: "Somente membros", feedBuilderMediaInherit: "Seguir configuração do feed", feedBuilderVideoOrder: "Ordem dos vídeos", feedBuilderFeedOrder: "Mais recentes primeiro", feedBuilderRecipeNeedsSource: "Selecione ao menos uma fonte", feedBuilderRecipeNeedsSourceHint: "Esta receita ficará vazia até que um canal, tag ou playlist seja selecionado.", feedBuilderConflict: "O construtor do feed foi alterado em outro lugar. A versão mais recente foi carregada.",
} satisfies Record<keyof typeof feedBuilderMessagesEn, string>;
