import type { publicSharingMessagesEn } from "./publicSharing.en";

export const publicSharingMessagesPl = {
  publicShareRateLimited: "Zbyt wiele żądań", publicShareRateLimitedHint: "Odczekaj chwilę i spróbuj ponownie otworzyć ten link.",
  publicShareUnavailable: "Ten link jest niedostępny", publicShareUnavailableHint: "Mógł zostać unieważniony lub zawieszony albo udostępniony element nie jest już dostępny.",
  publicShareLoading: "Wczytywanie udostępnionej zawartości…", publicSharePublicLink: "Link publiczny", publicShareEmptyPlaylist: "Brak dostępnych filmów", publicShareEmptyPlaylistHint: "Ta playlista nie zawiera obecnie filmów, które można pokazać publicznie.", publicSharePlaylist: "Udostępniona playlista", publicShareLoadMore: "Wczytaj więcej", publicShareNotFound: "Nie znaleziono udostępnionego linku",
  profilePermissionPublicSharing: "Udostępnianie publiczne", profilePermissionPublicSharingHint: "Tworzenie i zarządzanie publicznymi linkami do własnych filmów i playlist.",
  publicShareAction: "Link publiczny", publicShareCreate: "Utwórz link publiczny", publicShareDisabledByAdmin: "Udostępnianie publiczne zostało wyłączone przez administratora.", publicShareCopy: "Kopiuj link publiczny", publicShareCopied: "Skopiowano link publiczny", publicShareLocalMedia: "Zezwól na lokalne media", publicShareLocalMediaHint: "Pozwala odtwarzać lokalne media. Włączenie powoduje rotację linku.", publicShareRotate: "Zmień link", publicShareRotateConfirm: "Zmienić ten link? Poprzedni adres natychmiast przestanie działać.", publicShareRevoke: "Unieważnij link", publicShareRevokeConfirm: "Unieważnić ten publiczny link? Tej operacji nie można cofnąć.", publicShareActive: "Aktywny", publicShareSuspended: "Zawieszony", publicShareTokenRotated: "Link publiczny został zmieniony", publicShareError: "Nie udało się zaktualizować linku publicznego.",
  publicSharingSettingsNav: "Udostępnianie", publicSharingTitle: "Udostępnianie publiczne", publicSharingDescription: "Zarządzaj publicznymi linkami tylko do odczytu bez ujawniania profili ani pozostałej części aplikacji.", publicSharingMaster: "Włącz udostępnianie publiczne", publicSharingMasterHint: "Steruje wszystkimi publicznymi linkami w tej instalacji. Po wyłączeniu istniejące linki pozostają zapisane.", publicSharingLinks: "Linki publiczne", publicSharingLinksHint: "Dostęp do lokalnych mediów jest domyślnie wyłączony i ustawiany osobno dla każdego linku.", publicSharingEmpty: "Brak publicznych linków", publicSharingEmptyHint: "Utwórz link na stronie filmu lub playlisty.", publicShareOwner: "Właściciel: {name}", publicShareVideo: "Film", publicShareUserPlaylist: "Osobista playlista", publicShareFollowedPlaylist: "Obserwowana playlista", publicSharePolicyDisabled: "Udostępnianie jest globalnie wyłączone", publicSharePermissionSuspended: "Uprawnienie właściciela jest zawieszone", publicShareResourceUnavailable: "Zasób jest niedostępny",
} satisfies Record<keyof typeof publicSharingMessagesEn, string>;
