/** Regenerates app/src/timeZoneCoordinates.ts from the tzdata zone.tab that
 * ships with the operating system. The output is committed, so the application
 * never reads tzdata at runtime and the table cannot drift between hosts.
 *
 *   bun scripts/generate-timezone-coordinates.ts [path/to/zone.tab]
 */
import { readdir, readFile, stat, writeFile } from "node:fs/promises";
import { createHash } from "node:crypto";
import { join, relative } from "node:path";

const source = process.argv[2] ?? "/usr/share/zoneinfo/zone.tab";
const target = new URL("../app/src/timeZoneCoordinates.ts", import.meta.url);

/** zone.tab packs coordinates as ISO 6709: +DDMM+DDDMM or +DDMMSS+DDDMMSS. */
function parseCoordinates(field: string): { latitude: number; longitude: number } | null {
  const match = /^([+-]\d{4}(?:\d{2})?)([+-]\d{5}(?:\d{2})?)$/.exec(field);
  if (!match) return null;
  const degrees = (value: string, degreeDigits: number) => {
    const sign = value.startsWith("-") ? -1 : 1;
    const digits = value.slice(1);
    const deg = Number(digits.slice(0, degreeDigits));
    const min = Number(digits.slice(degreeDigits, degreeDigits + 2));
    const sec = digits.length > degreeDigits + 2 ? Number(digits.slice(degreeDigits + 2)) : 0;
    return sign * (deg + min / 60 + sec / 3600);
  };
  return {
    latitude: Math.round(degrees(match[1]!, 2) * 100) / 100,
    longitude: Math.round(degrees(match[2]!, 3) * 100) / 100,
  };
}

const lines = (await readFile(source, "utf8")).split("\n");
const entries: [string, number, number][] = [];
for (const line of lines) {
  if (!line || line.startsWith("#")) continue;
  const [, coordinates, zone] = line.split("\t");
  if (!coordinates || !zone) continue;
  const parsed = parseCoordinates(coordinates.trim());
  if (parsed) entries.push([zone.trim(), parsed.latitude, parsed.longitude]);
}
entries.sort((a, b) => a[0].localeCompare(b[0]));
if (entries.length < 300) throw new Error(`zone.tab yielded only ${entries.length} zones`);

// Legacy names such as US/Pacific or Europe/Kiev are links to a canonical zone
// in the compiled database, so identical file contents identify the alias. No
// JavaScript engine reliably canonicalizes them, and TZ is often set to one.
const root = source.replace(/\/zone\.tab$/, "");
const byDigest = new Map<string, string[]>();
async function collect(directory: string): Promise<void> {
  for (const item of await readdir(directory, { withFileTypes: true })) {
    const path = join(directory, item.name);
    if (item.isDirectory()) { await collect(path); continue; }
    if (!item.isFile()) continue;
    const zone = relative(root, path);
    if (zone.includes(".") || zone === "leapseconds" || zone === "tzdata.zi" || zone === "leap-seconds.list") continue;
    const contents = await readFile(path);
    if (contents.subarray(0, 4).toString() !== "TZif") continue;
    const digest = createHash("sha256").update(contents).digest("hex");
    byDigest.set(digest, [...(byDigest.get(digest) ?? []), zone]);
  }
}
const known = new Set(entries.map(([zone]) => zone));
const aliases: [string, string][] = [];
try {
  if ((await stat(root)).isDirectory()) await collect(root);
  for (const zones of byDigest.values()) {
    const canonical = zones.find((zone) => known.has(zone));
    if (!canonical) continue;
    for (const zone of zones) if (!known.has(zone)) aliases.push([zone, canonical]);
  }
} catch {
  console.warn("Could not scan the compiled zone files; the alias table will be empty.");
}
aliases.sort((a, b) => a[0].localeCompare(b[0]));

const rows = entries.map(([zone, latitude, longitude]) => `  "${zone}": [${latitude}, ${longitude}],`).join("\n");
const aliasRows = aliases.map(([alias, canonical]) => `  "${alias}": "${canonical}",`).join("\n");
await writeFile(target, `// Generated by scripts/generate-timezone-coordinates.ts from tzdata zone.tab.
// Do not edit by hand; rerun the script to refresh it.

/** Representative coordinates for each IANA zone, rounded to two decimals
 * (about a kilometre) because they only seed a default the operator can
 * override with their own latitude and longitude. */
const ZONE_COORDINATES: Readonly<Record<string, readonly [number, number]>> = {
${rows}
};

/** Legacy zone names that link to one of the entries above. */
const ZONE_ALIASES: Readonly<Record<string, string>> = {
${aliasRows}
};

export interface Coordinates {
  latitude: number;
  longitude: number;
}

export function timeZoneCoordinates(zone: string): Coordinates | null {
  const alias = ZONE_ALIASES[zone];
  const direct = ZONE_COORDINATES[zone] ?? (alias ? ZONE_COORDINATES[alias] : undefined);
  if (direct) return { latitude: direct[0], longitude: direct[1] };
  // UTC and the fixed-offset zones have no place on the map, but their offset
  // still puts the sun in roughly the right part of the sky.
  const offsetMatch = /^(?:Etc\\/)?(?:UTC|GMT|UCT|Universal|Zulu)(?:([+-])(\\d{1,2}))?$/.exec(zone);
  if (offsetMatch) {
    const hours = offsetMatch[2] ? Number(offsetMatch[2]) : 0;
    // POSIX-style Etc zones invert the sign: Etc/GMT+5 is five hours behind UTC.
    const signed = offsetMatch[1] === "+" ? -hours : hours;
    return { latitude: 0, longitude: Math.max(-180, Math.min(180, signed * 15)) };
  }
  return null;
}

export function timeZoneCount(): number {
  return Object.keys(ZONE_COORDINATES).length;
}
`, "utf8");
console.log(`Wrote ${entries.length} zones and ${aliases.length} aliases to app/src/timeZoneCoordinates.ts`);
